# -*- coding: utf-8 -*-
"""ATLAS-RL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtlQHUROntkrdDzfFHVcqlmcCvj_wBFL
"""

import subprocess, sys
for pkg in ["faiss-cpu", "sentence-transformers", "datasets"]:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

import os, gc, csv, random, time, warnings, types
warnings.filterwarnings("ignore")
os.environ["HF_HOME"]            = "/tmp/hf"
os.environ["TRANSFORMERS_CACHE"] = "/tmp/hf"
os.environ["HF_DATASETS_CACHE"]  = "/tmp/hf_ds"
os.makedirs("/tmp/hf",    exist_ok=True)
os.makedirs("/tmp/hf_ds", exist_ok=True)

import torch
import numpy as np
import faiss
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, AutoModelForSequenceClassification
from sentence_transformers import SentenceTransformer
from datasets import load_dataset
from typing import List, Dict, Optional, Tuple
from torch.optim import AdamW

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SEED   = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
print(f"[ATLAS-RL] Device: {DEVICE}")

CFG = dict(
    n_per        = 45,
    top_k        = 3,
    epochs       = 8,
    batch        = 2,
    w            = dict(alpha=0.35, beta=0.30, gamma=0.25, delta=0.10),
    res_csv      = "/content/sample_data/main_results.csv",
    abl_csv      = "/content/sample_data/ablation_results.csv",
)

def free():
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

NOISE = [
    "The quick brown fox jumps over the lazy dog.",
    "Irrelevant text with no useful information.",
    "This content is unrelated to any question.",
    "Random filler sentence for corruption tests.",
]

class RetrievalModule:
    def __init__(self):
        print("[Retrieval] Loading MiniLM ...")
        self.emb  = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device=DEVICE)
        self.idx  = None
        self.docs = []

    def build(self, documents):
        seen = list({d.strip()[:200] for d in documents if d.strip()})
        self.docs = seen
        embs = self.emb.encode(seen, batch_size=32, show_progress_bar=False,
                               normalize_embeddings=True).astype(np.float32)
        self.idx = faiss.IndexFlatIP(384)
        self.idx.add(embs)
        print(f"[Retrieval] {len(seen)} docs indexed")
        free()

    def get(self, query, k=2):
        if not self.idx or self.idx.ntotal == 0:
            return []
        q = self.emb.encode([query], normalize_embeddings=True).astype(np.float32)
        _, ii = self.idx.search(q, min(k, len(self.docs)))
        return [self.docs[i] for i in ii[0] if i < len(self.docs)]


class Perturber:
    def paraphrase(self, q):
        w = q.split()
        if len(w) < 3: return q
        i = random.randint(0, len(w)-2)
        w[i], w[i+1] = w[i+1], w[i]
        return " ".join(w).lower()

    def corrupt(self, docs, noise, ratio=0.5):
        out = list(docs)
        for i in range(max(1, int(len(out)*ratio))):
            if noise and i < len(out):
                out[i] = random.choice(noise)
        return out


class GenModule:
    def __init__(self, model_name="google/flan-t5-base"):
        print("[Gen] Loading flan-t5-base ...")
        self.tok = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(model_name, torch_dtype=torch.float32).to(DEVICE)
        self.model.eval()

    def _prompt(self, q, docs):
        ctx = " ".join(docs)[:250]
        return f"Context: {ctx}\nQuestion: {q}\nAnswer:"

    def gen_logits(self, q, docs):
        prompt = self._prompt(q, docs)
        enc = self.tok(prompt, return_tensors="pt", max_length=350,
                       truncation=True).to(DEVICE)
        with torch.no_grad():
            out = self.model.generate(
                **enc, max_new_tokens=40,
                output_scores=True, return_dict_in_generate=True,
                num_beams=1, do_sample=False,
            )
        ans = self.tok.decode(out.sequences[0], skip_special_tokens=True)
        tlp = torch.zeros(1)
        if out.scores:
            try:
                scores = torch.stack([s.float().cpu() for s in out.scores], dim=0)
                lp     = torch.log_softmax(scores, dim=-1)
                ids    = out.sequences[0][1:scores.shape[0]+1].cpu()
                ids    = ids.clamp(0, lp.shape[-1]-1)
                T      = min(lp.shape[0], len(ids))
                if T > 0:
                    tlp = lp[torch.arange(T), ids[:T]]
            except Exception:
                tlp = torch.zeros(1)
        del enc, out; free()
        return ans, tlp

    def gen_base(self, q):
        enc = self.tok(f"Question: {q}\nAnswer:", return_tensors="pt",
                       max_length=350, truncation=True).to(DEVICE)
        with torch.no_grad():
            out = self.model.generate(**enc, max_new_tokens=40,
                                      num_beams=1, do_sample=False)
        ans = self.tok.decode(out[0], skip_special_tokens=True)
        del enc, out; free()
        return ans


class NLIModule:
    def __init__(self):
        print("[NLI] Loading bart-large-mnli ...")
        name = "facebook/bart-large-mnli"
        self.tok   = AutoTokenizer.from_pretrained(name)
        self.model = AutoModelForSequenceClassification.from_pretrained(
            name, torch_dtype=torch.float32).to(DEVICE)
        self.model.eval()

    def _run(self, p, h):
        enc = self.tok(p[:350], h[:150], return_tensors="pt",
                       truncation=True, max_length=512).to(DEVICE)
        with torch.no_grad():
            logits = self.model(**enc).logits[0].float().cpu()
        probs = torch.softmax(logits, dim=-1).numpy()
        del enc, logits; free()
        return probs

    def entail(self, p, h):  return float(self._run(p,h)[2])
    def contra(self, p, h):  return float(self._run(p,h)[0])


class Diagnostics:
    def __init__(self, nli):
        self.nli = nli

    def consistency(self, a, pa):
        if not a.strip() or not pa.strip(): return 0.0
        return float((self.nli.entail(a,pa) + self.nli.entail(pa,a)) / 2)

    @staticmethod
    def uncertainty(tlp):
        if tlp is None or tlp.numel()==0: return 0.5
        v = -tlp.float().mean().item()
        return float(np.clip(1/(1+np.exp(-v+3)), 0, 1))

    def grounding(self, a, docs):
        if not docs or not a.strip(): return 0.0
        return self.nli.entail(" ".join(docs)[:350], a)

    def hallucination(self, a, docs):
        if not docs or not a.strip(): return 0.0
        return self.nli.contra(" ".join(docs)[:350], a)

    def run(self, a, pa, docs, tlp=None):
        return dict(
            consistency   = self.consistency(a, pa),
            uncertainty   = self.uncertainty(tlp),
            grounding     = self.grounding(a, docs),
            hallucination = self.hallucination(a, docs),
        )

    @staticmethod
    def failure(d):
        if d["hallucination"] > 0.5: return "hallucination"
        if d["grounding"]     < 0.3: return "retrieval_error"
        if d["consistency"]   < 0.4: return "inconsistency"
        return "none"


def kl(lp, lq):
    n = min(len(lp), len(lq))
    if n == 0: return 0.0
    a = lp[:n].float().clamp(-20,0)
    b = lq[:n].float().clamp(-20,0)
    return float(max((a.exp()*(a-b)).mean().item(), 0.0))

def reliability(tlp, ptlp, sc=5.0):
    return float(np.clip(1 - 1/(1+np.exp(-kl(tlp,ptlp)/sc+1)), 0, 1))

def atlas(R, G, C, U):
    w = CFG["w"]
    return float(np.clip(w["alpha"]*R + w["beta"]*G + w["gamma"]*C - w["delta"]*U, 0, 1))

def atlas_abl(R, G, C, U, nk=False, nc=False, ng=False):
    return atlas(0.5 if nk else R, 0.5 if ng else G, 0.5 if nc else C, U)

def tf1(p, r):
    ps, rs = set(p.lower().split()), set(r.lower().split())
    if not rs: return 0.0
    c = ps & rs
    if not c: return 0.0
    pr = len(c)/len(ps) if ps else 0
    rc = len(c)/len(rs)
    return 2*pr*rc/(pr+rc) if (pr+rc) > 0 else 0.0

def agg(preds, refs, diags, scores):
    return dict(
        token_f1           = float(np.mean([tf1(p,r) for p,r in zip(preds,refs)])),
        hallucination_rate = float(np.mean([d["hallucination"] for d in diags])),
        consistency        = float(np.mean([d["consistency"]   for d in diags])),
        grounding          = float(np.mean([d["grounding"]     for d in diags])),
        uncertainty        = float(np.mean([d["uncertainty"]   for d in diags])),
        atlas_score        = float(np.mean(scores)),
    )


def _syn(n, name):
    ts = ["photosynthesis","gravity","DNA","electricity","evolution",
          "climate","economics","history","mathematics","physics"]
    return [dict(query=f"What is {ts[i%10]}?",
                 answer=f"{ts[i%10]} is a fundamental concept.",
                 context=f"{ts[i%10]} involves complex processes with real-world applications.",
                 source=name) for i in range(n)]

def _try(fn, name, n):
    try: return fn()
    except Exception as e:
        print(f"[Data] fallback {name}: {e}"); return _syn(n, name)

def load_scienceqa(n):
    def _():
        ds = load_dataset("derek-thomas/ScienceQA","default",split=f"test[:{n}]",trust_remote_code=True)
        out=[]
        for ex in ds:
            ch=ex.get("choices",[]); idx=ex.get("answer",0)
            out.append(dict(query=ex.get("question",""),
                            answer=ch[idx] if ch and idx<len(ch) else "unknown",
                            context=ex.get("lecture","") or ex.get("solution",""),
                            source="ScienceQA"))
        return out
    return _try(_, "ScienceQA", n)

def load_tqa(n):
    def _():
        ds = load_dataset("truthful_qa","generation",split=f"validation[:{n}]",trust_remote_code=True)
        return [dict(query=ex["question"], answer=ex.get("best_answer",""),
                     context=ex.get("best_answer",""), source="TruthfulQA") for ex in ds]
    return _try(_, "TruthfulQA", n)

def load_fever(n):
    def _():
        ds = load_dataset("fever","v1.0",split=f"labelled_dev[:{n}]",trust_remote_code=True)
        m={"SUPPORTS":"true","REFUTES":"false"}
        return [dict(query=ex.get("claim",""), answer=m.get(ex.get("label",""),"unknown"),
                     context=ex.get("claim",""), source="FEVER") for ex in ds]
    return _try(_, "FEVER", n)

def load_nq(n):
    def _():
        ds = load_dataset("natural_questions",split=f"validation[:{n}]",trust_remote_code=True)
        out=[]
        for ex in ds:
            anns=ex.get("annotations") or {}
            sa=(anns.get("short_answers") or [{}])
            ans="unknown"
            if sa and isinstance(sa,list) and sa[0]:
                t=(sa[0].get("text",[]) if isinstance(sa[0],dict) else [])
                if t: ans=t[0]
            tok=(ex.get("document") or {}).get("tokens") or {}
            ctx=" ".join((tok.get("token") or [])[:120])
            q=ex.get("question") or {}
            out.append(dict(query=q.get("text","") if isinstance(q,dict) else "",
                            answer=ans, context=ctx, source="NQ"))
        return out
    return _try(_, "NQ", n)

def load_nocaps(n):
    def _():
        ds = load_dataset("HuggingFaceM4/NoCaps",split=f"validation[:{n}]",trust_remote_code=True)
        out=[]
        for ex in ds:
            ann=ex.get("annotations") or {}
            cap=(ann.get("raw") or ["unknown"])[0]
            out.append(dict(query="What is shown in this image?",
                            answer=str(cap)[:80], context=str(cap), source="VQA"))
        return out
    return _try(_, "VQA", n)

def load_all(n):
    print("[Data] Loading ...")
    all_s=[]
    for fn, nm in [(load_scienceqa,"ScienceQA"),(load_tqa,"TruthfulQA"),
                   (load_fever,"FEVER"),(load_nq,"NQ"),(load_nocaps,"VQA")]:
        s=fn(n); all_s.extend(s); print(f"  {nm}: {len(s)}")
    return all_s


class QADataset(torch.utils.data.Dataset):
    def __init__(self, Q, A, C, tok):
        self.Q=Q; self.A=A; self.C=C; self.tok=tok
    def __len__(self): return len(self.Q)
    def __getitem__(self, i):
        ctx=" ".join(self.C[i])[:250]
        p=f"Context: {ctx}\nQuestion: {self.Q[i]}\nAnswer:"
        s=self.tok(p,max_length=350,truncation=True,padding="max_length",return_tensors="pt")
        t=self.tok(self.A[i],max_length=40,truncation=True,padding="max_length",return_tensors="pt")
        lbl=t["input_ids"].squeeze().clone()
        lbl[lbl==self.tok.pad_token_id]=-100
        return dict(input_ids=s["input_ids"].squeeze(),
                    attention_mask=s["attention_mask"].squeeze(),labels=lbl)

def train_model(gen, ds, epochs=5, bs=2, lam=0.3, pre_a=None):
    loader = torch.utils.data.DataLoader(ds, batch_size=bs, shuffle=True, drop_last=True)
    opt    = AdamW(gen.model.parameters(), lr=3e-5, weight_decay=0.01)
    gen.model.train()
    for ep in range(1, epochs+1):
        losses=[]
        for step, batch in enumerate(loader):
            a_sc = float(np.mean(pre_a)) if pre_a else 0.5
            out  = gen.model(input_ids=batch["input_ids"].to(DEVICE),
                             attention_mask=batch["attention_mask"].to(DEVICE),
                             labels=batch["labels"].to(DEVICE))
            reward = torch.tensor(a_sc, device=DEVICE)
            loss = out.loss * (1.0 - reward)
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(gen.model.parameters(), 1.0)
            opt.step(); losses.append(loss.item())
            if (step+1)%20==0:
                print(f"  ep={ep} step={step+1} loss={np.mean(losses):.4f}")
            del out, loss; free()
        print(f"[Train] Epoch {ep}/{epochs} loss={np.mean(losses):.4f}")
    gen.model.eval()


def evaluate(samples, ret, gen, pert, diag, mode="rag"):
    preds, refs, diags, scores, fails = [], [], [], [], []
    for i, s in enumerate(samples):
        q   = (s["query"] or "What is the answer?").strip()
        ref = s["answer"]
        docs = ret.get(q, k=CFG["top_k"])
        if mode == "baseline":
            ans      = gen.gen_base(q)
            _, tlp   = gen.gen_logits(q, [])
            _, p_tlp = gen.gen_logits(pert.paraphrase(q), [])
            p_ans    = gen.gen_base(pert.paraphrase(q))
        else:
            ans,  tlp  = gen.gen_logits(q, docs)
            pq         = pert.paraphrase(q)
            pd         = pert.corrupt(docs, NOISE)
            p_ans, p_tlp = gen.gen_logits(pq, pd)

        d   = diag.run(ans, p_ans, docs, tlp)
        R   = reliability(tlp, p_tlp)
        asc = atlas(R, d["grounding"], d["consistency"], d["uncertainty"])

        preds.append(ans); refs.append(ref)
        diags.append(d);   scores.append(asc)
        fails.append(diag.failure(d))
        free()
        if (i+1)%20==0: print(f"  [{mode}] {i+1}/{len(samples)}")

    res = agg(preds, refs, diags, scores)
    res["fails"] = fails
    return res


def run_ablation(samples, ret, gen, pert, diag):
    cfgs = [
        dict(name="Full ATLAS",       nk=False, nc=False, ng=False),
        dict(name="w/o KL",           nk=True,  nc=False, ng=False),
        dict(name="w/o Consistency",  nk=False, nc=True,  ng=False),
        dict(name="w/o Grounding",    nk=False, nc=False, ng=True),
    ]
    sub = samples[:30]
    res = []
    for cfg in cfgs:
        al, fl = [], []
        for s in sub:
            q    = (s["query"] or "What is the answer?").strip()
            docs = ret.get(q, k=CFG["top_k"])
            a,  tlp  = gen.gen_logits(q, docs)
            pa, ptlp = gen.gen_logits(pert.paraphrase(q), pert.corrupt(docs,NOISE))
            d  = diag.run(a, pa, docs, tlp)
            R  = reliability(tlp, ptlp)
            sc = atlas_abl(R,d["grounding"],d["consistency"],d["uncertainty"],
                           nk=cfg["nk"],nc=cfg["nc"],ng=cfg["ng"])
            fl.append(tf1(a, s["answer"])); al.append(sc); free()
        res.append(dict(config=cfg["name"],
                        token_f1=float(np.mean(fl)),
                        atlas_score=float(np.mean(al))))
    return res


SEP  = "="*82
SEP2 = "-"*82

def ptable(rows, title, cols):
    print(f"\n{SEP}\n  {title}\n{SEP}")
    w=20
    print("  ".join(f"{c:<{w}}" for c in cols))
    print(SEP2)
    for r in rows:
        print("  ".join(f"{str(r.get(c,'')):<{w}}" for c in cols))
    print(SEP)

def scsv(rows, path):
    if not rows: return
    with open(path,"w",newline="") as f:
        writer=csv.DictWriter(f,fieldnames=rows[0].keys())
        writer.writeheader(); writer.writerows(rows)
    print(f"[CSV] {path}")

def f(v): return f"{v:.4f}" if isinstance(v,float) else str(v)


def main():
    t0=time.time()
    print(SEP)
    print("  ATLAS-RL | Reliability-Aware Training & Evaluation")
    print(f"  Device={DEVICE}  Seed={SEED}  n_per={CFG['n_per']}")
    print(SEP)

    samples = load_all(CFG["n_per"])
    corpus  = list({s["context"][:200] for s in samples if s["context"].strip()})

    ret  = RetrievalModule(); ret.build(corpus); free()
    gen  = GenModule();       free()
    pert = Perturber()
    nli  = NLIModule();       free()
    diag = Diagnostics(nli)

    print(f"\n[Eval] Baseline ...")
    base = evaluate(samples, ret, gen, pert, diag, mode="baseline")

    print(f"\n[Eval] RAG ...")
    rag  = evaluate(samples, ret, gen, pert, diag, mode="rag")

    print(f"\n[Train] ATLAS-RL ...")
    tr   = samples[:80]
    tr_c = [ret.get(s["query"], k=CFG["top_k"]) for s in tr]
    ds   = QADataset([s["query"] for s in tr],[s["answer"] for s in tr],tr_c,gen.tok)
    pre  = [random.uniform(0.4,0.7) for _ in tr]
    train_model(gen, ds, epochs=CFG["epochs"], bs=CFG["batch"], pre_a=pre)
    free()

    print(f"\n[Eval] ATLAS-RL model ...")
    arl  = evaluate(samples, ret, gen, pert, diag, mode="rag")

    def row(name, r):
        return {"Model":name,
                "Accuracy(F1)":  f(r["token_f1"]),
                "Hallucination": f(r["hallucination_rate"]),
                "Consistency":   f(r["consistency"]),
                "Grounding":     f(r["grounding"]),
                "ATLAS Score":   f(r["atlas_score"])}

    main_rows = [row("Baseline LLM",base), row("RAG",rag), row("ATLAS-RL",arl)]
    ptable(main_rows,"MAIN RESULTS",
           ["Model","Accuracy(F1)","Hallucination","Consistency","Grounding","ATLAS Score"])
    scsv(main_rows, CFG["res_csv"])

    print("\n[Ablation] ...")
    abl = run_ablation(samples, ret, gen, pert, diag)
    abl_rows=[{"Configuration":r["config"],"Token F1":f(r["token_f1"]),"ATLAS Score":f(r["atlas_score"])} for r in abl]
    ptable(abl_rows,"ABLATION STUDY",["Configuration","Token F1","ATLAS Score"])
    scsv(abl_rows, CFG["abl_csv"])

    all_f = base["fails"]+rag["fails"]+arl["fails"]
    fm={}
    for x in all_f: fm[x]=fm.get(x,0)+1
    tot=len(all_f)
    print(f"\n{SEP}\n  FAILURE MODE STATISTICS\n{SEP}")
    for k,v in sorted(fm.items(),key=lambda x:-x[1]):
        print(f"  {k:<25} {v:>4}  ({100*v/tot:.1f}%)")
    print(SEP)

    b,r,a=base,rag,arl
    def d(x,y): return f"{'↑' if x>y else '↓'}{abs(x-y):.4f}"
    print(f"\n{SEP}\n  KEY OBSERVATIONS\n{SEP}")
    print(f"  1. RAG vs Baseline   ATLAS {r['atlas_score']:.4f} vs {b['atlas_score']:.4f}  {d(r['atlas_score'],b['atlas_score'])}")
    print(f"  2. ATLAS-RL vs RAG   ATLAS {a['atlas_score']:.4f} vs {r['atlas_score']:.4f}  {d(a['atlas_score'],r['atlas_score'])}")
    print(f"  3. Hallucination     Base={b['hallucination_rate']:.4f} RAG={r['hallucination_rate']:.4f} ATLAS-RL={a['hallucination_rate']:.4f}")
    best=max(abl,key=lambda x:x["atlas_score"])
    worst=min(abl,key=lambda x:x["atlas_score"])
    print(f"  4. Best  ablation    '{best['config']}'  ATLAS={best['atlas_score']:.4f}")
    print(f"  5. Worst ablation    '{worst['config']}'  ATLAS={worst['atlas_score']:.4f}")
    top=max(fm,key=fm.get)
    print(f"  6. Top failure       {top}  ({100*fm[top]/tot:.1f}%)")
    print(f"\n  Runtime: {(time.time()-t0)/60:.1f} min")
    print(SEP)
    print(f"\n[DONE] {CFG['res_csv']}\n[DONE] {CFG['abl_csv']}")

main()